# Generated by Django 5.2.5 on 2025-08-16 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_file_path", models.FilePathField()),
                ("file_size", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("uploaded", "File Uploaded"),
                            ("converting", "Converting Audio Format"),
                            ("transcribing", "Transcribing with WhisperX"),
                            ("separating", "Separating Speakers"),
                            ("finalizing", "Finalizing Output"),
                            ("completed", "Processing Complete"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("speaker_count", models.IntegerField(blank=True, null=True)),
                ("output_directory", models.FilePathField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_id", models.CharField(max_length=50)),
                ("speaker_label", models.CharField(blank=True, max_length=100)),
                ("audio_file_path", models.FilePathField()),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_tracks",
                        to="processor.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["speaker_id"],
                "unique_together": {("job", "speaker_id")},
            },
        ),
    ]
